apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: update-delete-add-deploy
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50 
